#!/bin/bash
# encrypted tar with gpg
# targ -p <(echo $pass) <taropts>
case "$1" in
    -p) exec 3<"$2"
        shift 2
    ;;
    *)  echo "usage: $0 -p <password-file> <tar options>" >&2
        exit 1
    ;;
esac

tar "$@" -I $'bash -c \'gpg ${1:--c} --no-default-keyring --batch --passphrase-fd 3 --cipher-algo AES256\' _'
exec 3<&-

