#!/bin/bash
# encrypted tar with gpg
# targ -p <(echo $pass) <taropts>
case "$1" in
    -p) exec 3<"$2"
        shift 2
    ;;
    *)  [ -t ] && {
            read -s -p "Password: " pass
            echo ""
            exec 3< <(echo "$pass")
        } || exit 1
    ;;
esac
type gtar >/dev/null 2>&1 && tar=gtar || tar=tar

$tar "$@" -I $'bash -c \'gpg ${1:--c} --no-default-keyring --batch --passphrase-fd 3 --cipher-algo AES256\' _'
exec 3<&-

